Create Lookup Table Template [NSPECT-29]
NOAA-OCM/QNSPECT pull request #14
Opened 2021-10-07 19:33 UTC by idtodd

2021-10-07 20:33 UTC, ar-siddiqui requested changes

2021-10-07 20:33 UTC, ar-siddiqui commented on components/create_csvs/create_csvs.py
> +        self.addParameter(
I would suggest using feature sinks here. Something like this:

`        self.addParameter(QgsProcessingParameterFeatureSink('Outdefault', 'OutDefault', type=QgsProcessing.TypeVector, createByDefault=True, defaultValue=None))
`

or this 

`        self.addParameter(QgsProcessingParameterFileDestination('Htm', 'htm', optional=True, fileFilter='CSV files (*.csv)', createByDefault=True, defaultValue=None))`

2021-10-07 20:33 UTC, ar-siddiqui commented on components/create_csvs/create_csvs.py
> +        feedback = QgsProcessingMultiStepFeedback(0, model_feedback)
add feedback steps

2021-10-07 20:33 UTC, ar-siddiqui commented on components/create_csvs/create_csvs.py
> +            template = self.ncld_properties()
Here we should load a csv file into QGS Vector Layer class

2021-10-07 20:33 UTC, ar-siddiqui commented on components/create_csvs/create_csvs.py
> +        fieldnames = [
It would be better to separate data from code by loading the actual data from the CSV rather than having it in the code. Having it in the code makes it hard to read and edit later, and our code grows longer for no reason.

2021-10-07 21:00 UTC, ar-siddiqui commented on components/create_csvs/create_csvs.py
> +            template = self.ncld_properties()
https://github.com/ar-siddiqui/curve_number_generator/blob/2a407010130749a4ed22fe613c9f2e0432747561/curve_number_generator_algorithm.py#L200

Something like this.

2021-10-14 19:19 UTC, ar-siddiqui requested changes
[NSPECT-29] [NSPECT-46]

2021-10-14 19:19 UTC, ar-siddiqui commented on resources/coefficients/CCAP.csv
> +lu_value,lu_name,cn_a,cn_b,cn_c,cn_d,c_factor,tss,lead,zinc,nitrogen,phosphorus
Can you please multiply the CN value columns (all four) by 100 so that let's say 0.89 will become 89. CN values are supposed to be 1 to 100. Not sure why they did 0 to 1.

2021-10-14 19:19 UTC, ar-siddiqui commented on resources/coefficients/NLCD.csv
> +lu_value,lu_name,cn_a,cn_b,cn_c,cn_d,c_factor,tss,lead,zinc,nitrogen,phosphorus
Can you please multiply the CN value columns (all four) by 100 so that let's say 0.89 will become 89. CN values are supposed to be 1 to 100. Not sure why they did 0 to 1.

2021-10-14 19:19 UTC, ar-siddiqui commented on components/create_lookup_table_template/create_lookup_table_template.py
> +COEFFICIENTS_PATH = r"C:\Projects\work\nspect\QNSPECT\resources\coefficients\{0}.csv"
I am getting this error when using the NLCD option while the CCAP is working fine. Not sure why. Can you confirm you are not having the same issue?

![image](https://user-images.githubusercontent.com/53625184/137378978-825e493f-a3fd-40a8-b618-42b3106f0fdf.png)

2021-10-14 19:19 UTC, ar-siddiqui commented on components/create_lookup_table_template/create_lookup_table_template.py
> +            QgsProcessingParameterFileDestination(
I tried giving this script to Graphic Modeler, it didn't like the output format and hence gave this error. I think we will have to use the proper Sink `self.addParameter(QgsProcessingParameterFeatureSink('Outdefault', 'OutDefault', type=QgsProcessing.TypeVector, createByDefault=True, supportsAppend=True, defaultValue=None))`

See how the input is None in Step 2, I tried passing the Output of 1 to 2.
![image](https://user-images.githubusercontent.com/53625184/137380777-f4861e04-a461-4d6f-ae47-64ac573a5f00.png)

We want this Algorithm to run in Graphic Model. Users would like to change coefficients and run multiple scenarios.

2021-10-14 19:19 UTC, ar-siddiqui commented on components/create_lookup_table_template/create_lookup_table_template.py
> +        add_layer = self.parameterAsBool(parameters, "OpenOutputFile", context)
If we use the proper sink. We don't need to do the line 79 through 92. We should be able to load the coefficients CSV as QGIS Vector Layer then pass this to the sink as was suggested in the last review and it will take care of everything including load in canvas or not. Thus making the code much compact.

2021-10-14 19:19 UTC, ar-siddiqui commented on components/create_lookup_table_template/create_lookup_table_template.py
> +        add_layer = self.parameterAsBool(parameters, "OpenOutputFile", context)
If this doesn't work let me know.

2021-10-14 19:19 UTC, ar-siddiqui commented on components/create_csvs/create_csvs.py
> +            template = self.ncld_properties()
This will help when you use Vector Sink

2021-10-14 19:19 UTC, ar-siddiqui commented on components/create_csvs/create_csvs.py
> +from qgis.core import (
This file is no longer needed. Hence should be deleted.

2021-10-15 19:12 UTC, idtodd commented on components/create_lookup_table_template/create_lookup_table_template.py
> +COEFFICIENTS_PATH = r"C:\Projects\work\nspect\QNSPECT\resources\coefficients\{0}.csv"
There was a misspelling spelling. I added the names as a class property, so that should fix it up and make it easier to manage.

2021-10-19 20:58 UTC, ar-siddiqui approved these changes

2021-10-19 20:58 UTC, merged