Help and documentation for Rasterize Soils and Align Rasters [NSPECT-50]
NOAA-OCM/QNSPECT pull request #16
Opened 2021-10-15 13:19 UTC by idtodd

closes #11

2021-10-18 14:20 UTC, ar-siddiqui requested changes

2021-10-18 14:20 UTC, ar-siddiqui commented on components/rasterize_soil/rasterize_soil.py
> +<p>Soils data are used to estimate sediment loads. Two soil parameters are needed: the hydrologic soils group, which is a measure of how permeable the soils are; and the K-factor, which is a measure
`Soils data are used to estimate sediment loads` I think this is good to include in the user guide to provide context, but it is irrelevant for the tool help.

2021-10-18 14:20 UTC, ar-siddiqui commented on components/rasterize_soil/rasterize_soil.py
> +<p>Soils data are used to estimate sediment loads. Two soil parameters are needed: the hydrologic soils group, which is a measure of how permeable the soils are; and the K-factor, which is a measure
The same goes for sentences about getting data from SSURGO.

2021-10-18 14:20 UTC, ar-siddiqui commented on components/rasterize_soil/rasterize_soil.py
> +<p>Field of the Soil Layer representing the hydrologic soil group (HSG). The picklist values comes from the fields in the Soil Layer. This will default to 'hydgrpdcd' if it is present in the Soil Lay
`This will default to 'hydgrpdcd' if it is present in the Soil Layer.`
This may create confusion for the users who may think that if hydgrpdcd is present in the layer it will always be used irrespective of input. What do you think? This may be omitted.

2021-10-18 14:20 UTC, ar-siddiqui commented on components/rasterize_soil/rasterize_soil.py
> +<p>The only valid values for this field are 'A', 'B', 'C' , 'D', 'A/D', 'B/D', 'C/D', 'W', and Null. If the field contains any values other than these, the tool will terminate without output.</p>
This is for Hydrologic Soil Group Layer not K-Factor

2021-10-18 14:20 UTC, ar-siddiqui commented on components/rasterize_soil/rasterize_soil.py
> +<p>The cell size of the output raster(s). The units will default to the units of the CRS of the Soil Layer.</p>
The units will default to the units of the CRS of the Soil Layer `if no other units are specified`

2021-10-18 14:20 UTC, ar-siddiqui commented on components/rasterize_soil/rasterize_soil.py
> +<p>The output location of the Hydrologic Soil Group raster. The raster will inherit the CRS of the Soil Layer.</p>
`The output path` is better since this is not the parent folder but the actual path.

2021-10-18 14:20 UTC, ar-siddiqui commented on components/rasterize_soil/rasterize_soil.py
> +<p>The output location of the K-Factor raster. The raster will inherit the CRS of the Soil Layer.</p>
`The output path` is better since this is not the parent folder but the actual path.

2021-10-18 14:20 UTC, ar-siddiqui commented
closes #11

2021-11-23 17:22 UTC, idtodd commented on components/rasterize_soil/rasterize_soil.py
> +<p>Field of the Soil Layer representing the hydrologic soil group (HSG). The picklist values comes from the fields in the Soil Layer. This will default to 'hydgrpdcd' if it is present in the Soil Lay
Maybe we should include this in any user guide to explain its behavior, but I think it's fine to omit it here.

2021-11-23 19:03 UTC, ar-siddiqui approved these changes

2021-11-23 19:03 UTC, merged