Modify Land Use Tool
NOAA-OCM/QNSPECT pull request #19
Opened 2021-11-08 18:46 UTC by idtodd

Added two modules to supplement the original Modify Land Use modules.
1) Modify Land Use by NLCD/CCAP: Reads the coefficient CSVs and puts them in a dropdown for the user.
2) Modify Land Use by Name: Uses a user-input modified CSV to set the raster value by the name of the land use.

2021-11-09 17:42 UTC, ar-siddiqui requested changes
Great work overall. Please address these minor comments.

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_field.py
At line 42, the output display name should be `Modified Land Use`

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_field.py
At line 21. The Areas to modify should only take Polygon, like it is happening in Modify Land Use by Name.

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_name.py
> +                "Coefficients Table",
I would suggest naming this one `Land Use Lookup Table` the same thing we are calling it at other places.

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_name.py
> +                self.output, "Modified Raster", createByDefault=True, defaultValue=None
Change to `Modified Land Use`

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_name.py
> +        # Use only the selected features of the vector layer
This is an excellent idea. There is a standard (and cleaner) way to do this.

If you use the following input parameter, it will take care of this. You will have to test though. I think this should be applied across all three.

`        self.addParameter(QgsProcessingParameterFeatureSource('AreastoModify', 'Areas to Modify', types=[QgsProcessing.TypeVectorPolygon], defaultValue=None))
`
![image](https://user-images.githubusercontent.com/53625184/140973902-c8f6efbb-058c-4a9b-999f-99ecd90b3b5e.png)

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_name.py
> +        return "Modify Land Use by Name"
Change the name to `Modify Land Use (Custom Lookup Table)` to be consistent with other tools.

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_field.py
> +        return "Modify Land Use by Field"
Let's change the name to `Modify Land Use (Vector Field)` we will follow this naming convention to put additional details. This is the same as other QGIS tools.

![image](https://user-images.githubusercontent.com/53625184/140975057-e550a0be-1fcb-44a2-89e7-bb624206bbca.png)

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_name.py
> +                "Area to Change",
Change to `Areas to Modify` to be consistent.

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +                self.output, "Modified Raster", createByDefault=True, defaultValue=None
Change to `Modified Land Use`

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +                "Area to Change",
Change to `Areas to Modify`

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +                "Land Use",
Should we call it something like `Land Use to Apply` `New Land Use`. I can't think of a good name, but the idea is it should be a bit more descriptive.

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +        self.coefficients: Dict[str, int] = {}
This is excellent.

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +        if len(vector_layer.selectedFeatures()):
Same comment as in previous file.

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +        return f"Modify Land Use by NLCD/CCAP"
Change to `Modify Land Use (NLCD/CCAP)`

2021-11-09 17:42 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +        return f"Modify Land Use by NLCD/CCAP"
Change here as well. This will happen in all three modules.

2021-11-11 16:31 UTC, idtodd commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +                "Land Use",
Changed to `Name of Land Use to Apply`

2021-11-16 15:12 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_field.py
> +                "Area to Modify",
Any reason why we changed Areas to Area ?

2021-11-16 15:12 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +                "Land Use",
This should happen in Modify Land Use (Custom) as well.

2021-11-16 15:13 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_nlcdccap.py
> +        return f"Modify Land Use by NLCD/CCAP"
Please do this in all three modules.

2021-11-16 16:14 UTC, idtodd commented on components/modify_land_use/modify_land_use_by_field.py
> +                "Area to Modify",
It made more sense to have it plural if the input has multiple features with multiple land use types.

2021-11-16 16:16 UTC, ar-siddiqui commented on components/modify_land_use/modify_land_use_by_field.py
> +                "Area to Modify",
Ok marking resolved.

2021-11-17 17:14 UTC, ar-siddiqui approved these changes

2021-11-17 17:14 UTC, merged