Align Raster fails using a geographic projected shapefile for clipping extent [NSPECT-55]
NOAA-OCM/QNSPECT pull request #20
Opened 2021-11-08 19:47 UTC by idtodd

Align Rasters module now reprojects the input vector feature to the CRS of the input raster. This prevents extent buffers that can be unexpectedly large when using a geographic CRS as a vector input.

2021-11-09 19:21 UTC, ar-siddiqui requested changes

2021-11-09 19:21 UTC, ar-siddiqui commented on components/align_rasters/align_rasters.py
> +            raster = self.parameterAsRasterLayer(parameters, "ReferenceRaster", context)
We are already doing this at 174, so move 174 before the if statement and we wouldn't need this.

2021-11-09 19:21 UTC, ar-siddiqui commented on components/align_rasters/align_rasters.py
> +            raster_crs = raster.crs()
Can we call it `ref_rast_crs`

2021-11-09 19:21 UTC, ar-siddiqui commented on components/align_rasters/align_rasters.py
> +            # Reproject layer
Change this comment to remember why we did this
```
# Reprojecting Buffer Extent Layer to Reference Raster CRS because 
# Clipping extent and Buffer distance can be in different CRS
# If the distance is in projected units (meters etc) and Clipping Extent in Geographic (degrees)
# the buffer algorithm will treat distance in degrees ignoring actual buffer distance units
```

2021-11-09 19:21 UTC, ar-siddiqui commented on components/align_rasters/align_rasters.py
> +                    feedback.pushWarning(
We should report the error here and fail the algorithm rather than changing a user input ourselves.

2021-11-09 19:21 UTC, ar-siddiqui commented on components/align_rasters/align_rasters.py
> +            units = QgsUnitTypes.toString(raster_crs.mapUnits())
Though this would work (because if raster CRS is in degrees buffer distance units will always be degrees as well), it would be better to take units from buffer distance rather than raster CRS.

2021-11-09 19:22 UTC, ar-siddiqui commented
@idtodd Once you make the requested changes please do testing with different combinations of geographic and projected Rasters and Vectors.

2021-11-11 16:12 UTC, idtodd commented
Changes requested were made or became irrelevant. The reference raster will now be required to have a projected CRS.

2021-11-16 14:31 UTC, ar-siddiqui approved these changes

2021-11-16 14:38 UTC, merged