Round cell size to nearest integer [NSPECT-61]
NOAA-OCM/QNSPECT pull request #23
Opened 2021-11-16 17:43 UTC by idtodd

Output raster size is rounded to the nearest integer. Added an option to set the output raster resolution rather than always adopting it from the reference raster.

2021-11-18 17:38 UTC, ar-siddiqui requested changes
@idtodd please address these comments

2021-11-18 17:38 UTC, ar-siddiqui commented on components/align_rasters/align_rasters.py
> +                type=QgsProcessingParameterNumber.Integer,
We should allow non-integers here as well. If users wants to put integer value they can always do that.

2021-11-18 17:38 UTC, ar-siddiqui commented on components/align_rasters/align_rasters.py
> +                minValue=1,
min value should be 0 or just greater than 0 (0.0000000000000000000000001) something like this not sure if it is a good idea or not.

2021-11-23 17:33 UTC, idtodd commented on components/align_rasters/align_rasters.py
> +                minValue=1,
Set to 0.000001 Since that's the smallest where it will show as non-zero in the GUI.

2021-11-23 18:53 UTC, ar-siddiqui approved these changes

2021-11-23 19:01 UTC, merged