Run Erosion Analysis [NSPECT-54]
NOAA-OCM/QNSPECT pull request #33
Opened 2022-01-20 16:44 UTC by idtodd

Module for running the erosion analysis version of the QNSPECT package.

closes #44

2022-01-27 16:43 UTC, ar-siddiqui requested changes
- [x] The algorithm is not working.

![image](https://user-images.githubusercontent.com/53625184/151391844-980c4e9a-fd8d-4fb3-8d0d-5277f53e114b.png)

- [x] Please address all comments and do thorough testing before resubmitting for review.

- [x] Merge dev branch to bring in plugin template and adjust your code accordingly.

- [x] Refactor other components if you are creating common functions that can be utilized in other components

- [x] Please add high-level explanatory comments to your code so that other reviewers and developers can understand what is going on. Not just what the code is doing but why you are asking code to do what you asked it to do.

- [x] Please add a docstring to functions, especially if the name is not self-explanatory.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +    def _fill_elevation_depression(self):
Is there a reason to fill the DEM?
GRASS's official stance is that r.watershed does not need filled DEM, but if the user like they can do it externally, I don't think we should fill the DEM silently if there is no obvious reason to do so.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +            output=r"C:\Projects\work\nspect\workspace\scenarios\New folder\rl_raster.tif",
Please fix this.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +            feedback=self.feedback,
Do not pass feedback object to GRASS functions.
GRASS spits a lot of error messages that are not useful for our purposes.
By not passing the feedback object, these messages will not be displayed in the log of our algorithm.
![image](https://user-images.githubusercontent.com/53625184/151386818-7b25c3c0-43b5-4cdc-9221-17d2e1e3c066.png)

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +        land_use_raster = convert_raster_data_type_to_float(
Please explain in the comments why is this necessary, for future developers and reviewers.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +            QgsProcessingParameterRasterLayer(
Move the Land Use Raster down so that it is just above other land use parameters.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +                self.rainfallRaster, "R-Factor Raster (Rainfall)", defaultValue=None,
It is confusing to call this raster rainfall. It gives a message that it is the same as precipitation raster from pollution analysis when it is not. If agreed, please change in GUI and code.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +                self.soilsRasterRaw, "Soils Raster", defaultValue=None
Change `Soils` to `Soil` to be consistent with `pollution analysis`.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +                self.soilsRaster, "K-factor Raster (Soils)", defaultValue=None
It is confusing to call this raster Soils. It gives a message that it is the same as soil raster when it is not. Please change in code and GUI.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +                options=list(LAND_USE_TABLES.values()) + ["Custom"],
Custom's int value is reserved for 0, similarly C-CAP: 1, and NLCD:2. This is for the reason that if in future land uses are added our old configuration files are still compatible.

Also, you can not use .values() as dict data type does not have any order. Order is important here because `load previous analysis` assumes that the input lists are ordered.

https://github.com/Dewberry/QNSPECT/blob/3f3bef3ebe942a16caae0e11029b883ce159f327/algorithms/run_analysis/run_pollution_analysis.py#L154

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/analysis_utils.py
> +LAND_USE_TABLES = {0: "NLCD", 1: "C-CAP"}
Use similar mapping as pollution analysis. 0 is reserved for Custom lookup type.
https://github.com/Dewberry/QNSPECT/blob/3f3bef3ebe942a16caae0e11029b883ce159f327/algorithms/run_analysis/run_pollution_analysis.py#L86

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/analysis_utils.py
> +def filter_matrix(matrix: list) -> list:
We already have this in qnspect_utils

https://github.com/Dewberry/QNSPECT/blob/3f3bef3ebe942a16caae0e11029b883ce159f327/algorithms/qnspect_utils.py#L12

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/analysis_utils.py
> +def perform_raster_math(
We already have this function, what is the need for this function again?

https://github.com/Dewberry/QNSPECT/blob/3f3bef3ebe942a16caae0e11029b883ce159f327/algorithms/qnspect_utils.py#L21

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/analysis_utils.py
> +def assign_land_use_field_to_raster(
Good thought to make these functions generic, but the name here is confusing, please choose a generic name. Explain what function does in the docstring, and remove original function here.

https://github.com/Dewberry/QNSPECT/blob/3f3bef3ebe942a16caae0e11029b883ce159f327/algorithms/run_analysis/run_pollution_analysis.py#L542

You should also adjust this

https://github.com/Dewberry/QNSPECT/blob/3f3bef3ebe942a16caae0e11029b883ce159f327/algorithms/run_analysis/run_pollution_analysis.py#L339

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/analysis_utils.py
> +    if output is None:
Create a docstring.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/analysis_utils.py
> +    if parameters[alg.lookupTable]:
https://github.com/Dewberry/QNSPECT/blob/3f3bef3ebe942a16caae0e11029b883ce159f327/algorithms/run_analysis/run_pollution_analysis.py#L264-L278

- [ ] I think this is more appropriate logic because of the reserved int for each land use type.
- [ ] Since you are creating a common function, you should remove this part from `run_pollution_analysis`

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/analysis_utils.py
> +def grass_material_transport(
Again, if you are moving around functions, please remove them from the original place and edit references accordingly as well.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/relief_length_ratio.py
> +def run_raster_calculation(
This function is pretty similar to `perform_raster_maths` if this is only being used in one place, it would make more sense to not have this function. What do you think about preparing inputs in the main function and just calling `perform_raster_maths`.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/relief_length_ratio.py
> +    # QGIS Native Slope
Is QGIS native slope and GRASS slope the same?

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +DEFAULT_URBAN_K_FACTOR_VALUE = 0.3
Do not forget to include this in documentation.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +            feedback.pushError("Invalid Elevation Raster CRS units.")
Use `QgsProcessingException` to report errors. (typical)

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +        # K-factor - soil erodability
Thanks for these code comments.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +    def cell_size_in_meters(self, parameters, context):
I think you mean to write sq_meters.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +        self._run_watershed()
I think you should take out this function from the init block. It is a code practice to keep the init block as lean as possible so as to not crash the class on initialization if there are any issues.

You can delete this here and make the `_run_watershed` public. Then call it in your main code to run watershed.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +            "drainage": QgsProcessing.TEMPORARY_OUTPUT,
No need to calculate this if we are not using it anywhere.

2022-01-27 16:43 UTC, ar-siddiqui commented on components/run_analysis/run_erosion_analysis.py
> +            "slope_steepness": QgsProcessing.TEMPORARY_OUTPUT,
No need to calculate this if we are not using it anywhere.

2022-01-27 17:43 UTC, idtodd commented on components/run_analysis/analysis_utils.py
> +LAND_USE_TABLES = {0: "NLCD", 1: "C-CAP"}
Looks like I was referencing an older version of the items.

2022-01-27 17:44 UTC, idtodd commented on components/run_analysis/run_erosion_analysis.py
> +                options=list(LAND_USE_TABLES.values()) + ["Custom"],
As of python 3.6, dictionaries maintain insertion error.

2022-01-27 17:47 UTC, idtodd commented on components/run_analysis/run_erosion_analysis.py
> +    def _fill_elevation_depression(self):
I remember seeing something about not needing to fill the DEM only if you're using MDF. I can't find it again, and it's not mentioned in the current documentation, so I'll remove that from the process.

2022-01-27 18:34 UTC, idtodd commented on components/run_analysis/relief_length_ratio.py
> +    # QGIS Native Slope
No. GRASS' slope has a lot more stuff to it. I don't think bells and whistles are needed here, so I'm going with the native one.

2022-01-27 18:57 UTC, idtodd commented on components/run_analysis/run_erosion_analysis.py
> +        self._run_watershed()
Replaced the watershed class with a different method. Earlier versions of trying to work through how to calculate the LS factor made the other outputs of GRASS watershed useful, but now we just need that single raster from the calculation.

2022-02-02 22:11 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +                sediment_local, "Local Accumulation (kg)", context
This should be `Sediment Local (kg)` ?

2022-02-02 22:12 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +    sedimentYieldLocal = "SedimentLocal"
Is there a reason why we are not putting space in between like `Sediment Local`. This is not a coding variable but the user output, so I guess spaces would be fine. But if you think files should not have spaces in name, lets discuss, in that case we should remove the spaces from output of all other tools as well especially `Run Pollution Analysis`

2022-02-03 12:51 UTC, idtodd commented on algorithms/run_analysis/run_erosion_analysis.py
> +    sedimentYieldLocal = "SedimentLocal"
I didn't realize they were tied to output that way — I had seen it as an internal naming scheme for storing and retrieving outputs/results. Let's make it use spaces.

2022-02-03 14:20 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +    sedimentYieldLocal = "SedimentLocal"
@idtodd with new names, will the Comparison tool be able to recognize the outputs?

2022-02-09 15:45 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +        lookup_layer = extract_lookup_table(self, parameters, context)
I don't like the fact that we are passing the whole class instance to an outside function, class methods are there exactly to do just that.
1. Either the function should only take what it needs, meaning just the `self.parameterAsVectorLayer` function as a parameter
2. We should create a superclass that implements this method, or
3. This function should be written separately for  both

2022-02-09 15:46 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +            lookup_layer=extract_lookup_table(self, parameters, context),
Why are we extracting lookup_layer three times?
You already have lookup_layer at 156, use that.

2022-02-09 15:47 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +        lookup_layer = extract_lookup_table(self, parameters, context)
Why are we extracting lookup_layer three times?
You already have lookup_layer at 156, use that.

2022-02-09 15:59 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +        lookup_layer = extract_lookup_table(self, parameters, context)
I don't like the fact that we are passing the whole class instance to an outside function, class methods are there exactly to do just that.

1. Either the function should only take what it needs, meaning just the self.parameterAsVectorLayer function as a parameter
2. We should create a superclass that implements this method, or
3. This function should be written separately for both

I would suggest going with 1 or 3, although 2 is most technically correct.

2022-02-09 15:59 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +            lookup_layer=extract_lookup_table(self, parameters, context),
Why are we extracting lookup_layer three times?
You already have lookup_layer at 156, use that.

2022-02-09 15:59 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +        lookup_layer = extract_lookup_table(self, parameters, context)
Why are we extracting lookup_layer three times?
You already have lookup_layer at 156, use that.

2022-02-09 15:59 UTC, ar-siddiqui commented on components/run_analysis/relief_length_ratio.py
> +    # QGIS Native Slope
But the actual value of the slope is the same, right? I am just being careful that we are not using apples as oranges.

2022-02-09 16:07 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +                sediment_local, "Local Accumulation (kg)", context
I still see this as `Local Accumulation (kg)`

2022-02-09 16:18 UTC, ar-siddiqui requested changes
- [ ] One general theme that I noticed is that there is a lot of repetition when it comes to extracting parameters as layers. You should only do that once in the main function, and then pass those layers to other functions as parameters. It solves two things:
1. You only perform this operation once
2. Your functions are lean (one function doing only one thing)

- [ ] There are duplicate files in both algorithms folder and run_analysis folders, the one in algorithm folders should be deleted

2022-02-09 16:18 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +        param = QgsProcessingParameterBoolean(
GRASS LS Calcultor does not utilize MFD for LS Factor. So there is no difference between checking this option or not.
MFD should be deleted from this algorithm, and it should be documented that this algorithm utilizes SFD only.

More details here https://github.com/OSGeo/grass/issues/2033

2022-02-09 16:18 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +        config["Inputs"][self.elevationRaster] = self.parameterAsRasterLayer(
We already extracted DEM twice, this is the third time I believe.

2022-02-09 16:18 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +    def create_ls_factor(self, parameters, context, outputs):
We don't need outputs here. You can return something like this

```
return processing.run(
            "grass7:r.watershed",
            alg_params,
            context=context,
            feedback=None,
            is_child_algorithm=True,
        )["length_slope"]
```

2022-02-09 16:18 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +    def create_ls_factor(self, parameters, context, outputs):
Output is a dict from another algorithm that contains a lot of irrelevant data as well.

2022-02-09 16:45 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +                sediment_local, "Local Accumulation (kg)", context
Ok, I see now, I was looking at the duplicate file. Please delete duplicate files.

2022-02-09 17:04 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +                sediment_local, "Local Accumulation (kg)", context
I deleted duplicate files

2022-02-09 17:18 UTC, idtodd commented on components/run_analysis/relief_length_ratio.py
> +    # QGIS Native Slope
QGIS and GRASS are basically the same. Searching around a quick test, the values are either the same or within 8 significant digits. IIRC, we decided to try to preference native QGIS tools when available, so this seems like the right call.

2022-02-09 17:36 UTC, idtodd commented on algorithms/run_analysis/run_erosion_analysis.py
> +        lookup_layer = extract_lookup_table(self, parameters, context)
If we were starting from scratch, I'd probably go with 2 (since there are enough other things that get shared between the algorithm classes), but for time's sake, I went with 1.

2022-02-09 20:54 UTC, ar-siddiqui commented on algorithms/run_analysis/run_erosion_analysis.py
> +    sedimentYieldLocal = "SedimentLocal"
@idtodd I don't think this has been addressed and I am getting the expected error. Why was it marked resolved?

![image](https://user-images.githubusercontent.com/53625184/153288132-acef1935-349a-41cd-9bca-cb5a154dceae.png)

![image](https://user-images.githubusercontent.com/53625184/153288220-44925ea8-18cd-47df-99bc-1fea8bd3e8c8.png)

2022-02-10 02:45 UTC, ar-siddiqui commented
Closes #44

2022-02-10 02:47 UTC, ar-siddiqui approved these changes

2022-02-10 02:47 UTC, merged