Check raster values are in lookup table [NSPECT-70]
NOAA-OCM/QNSPECT pull request #48
Opened 2022-02-10 13:30 UTC by idtodd

Function added to check that all of the values in a raster have a corresponding value in the lookup layer.

2022-02-14 21:41 UTC, ar-siddiqui requested changes
@idtodd Please make the suggested changes.

2022-02-14 21:41 UTC, ar-siddiqui commented on algorithms/run_analysis/analysis_utils.py
> +        "OUTPUT_HTML_FILE": QgsProcessing.TEMPORARY_OUTPUT,
Why not use the table rather than HTML that would save a lot of code work.

```python
        alg_params = {
            'BAND': 1,
            'INPUT': raster,
            'OUTPUT_TABLE': QgsProcessing.TEMPORARY_OUTPUT
        }
```

2022-02-14 21:41 UTC, ar-siddiqui commented on algorithms/run_analysis/analysis_utils.py
> +    html_file = processing.run(
```python
      unique_table = processing.run('native:rasterlayeruniquevaluesreport', alg_params, context=context, feedback=feedback, is_child_algorithm=True)['OUTPUT_TABLE']
```

2022-02-14 21:41 UTC, ar-siddiqui commented on algorithms/run_analysis/analysis_utils.py
> +            if float(num) not in lu_codes:
You may need to see if set operations can be used here to find the difference, set operations are usually very fast.

2022-02-14 21:41 UTC, ar-siddiqui commented on algorithms/run_analysis/analysis_utils.py
> +    with open(html_file) as file:
This would be very easy if you use the table rather than HTML file

2022-02-14 21:45 UTC, ar-siddiqui commented on algorithms/run_analysis/analysis_utils.py
> +            if float(num) not in lu_codes:
Also will `in` work for cases like let's say Lu Table value 1 vs Lu Raster value 1.0?

2022-02-15 23:00 UTC, idtodd commented on algorithms/run_analysis/analysis_utils.py
> +        "OUTPUT_HTML_FILE": QgsProcessing.TEMPORARY_OUTPUT,
My first instinct was to use a known HTML file location string output than an unknown output table type. The code's been updated to check if the output table is a string and try to convert it to a QgsVectorLayer if it isn't.

2022-02-15 23:01 UTC, idtodd commented on algorithms/run_analysis/analysis_utils.py
> +            if float(num) not in lu_codes:
Changed to a set, and it will equivocate floats and ints.

2022-02-16 19:33 UTC, ar-siddiqui approved these changes

2022-02-16 19:33 UTC, merged